


const ScheduleOfODrivers = ({
    titleSection,
    t1,
    t2,
    t3,
    t4,
    t5,
    t6,
    data,
    setData,
    c1,
    c2,
    c3,
    c4,
    c5,
    c6,
    name,
    require
  }) => {
    const handlerData = (e) => {
      if (name === "scheduleOfDrivers") {
        setData({
          ...data,
          scheduleOfDrivers: {
            ...data.scheduleOfDrivers,
            [e.target.id]: {
              ...data.scheduleOfDrivers[e.target.id],
              [e.target.name]: e.target.value,
            },
          },
        });
      }

      if (name === "vehicleSchedule") {
        setData({
          ...data,
          vehicleSchedule: {
            ...data.vehicleSchedule,
            [e.target.id]: {
              ...data.vehicleSchedule[e.target.id],
              [e.target.name]: e.target.value,
            },
          },
        });
      }
    };

    return (
      <>
        <div className="title is-3">{titleSection}{
          require ? <span className="requiredata">*</span> : null
        }</div>
        <div className="columns">
          <div className="column">
            <div className="table-container">
              <table className="table is-hoverable is-striped is-fullwidth">
                <thead>
                  <tr>
                    <th>{t1}</th>
                    <th>{t2}</th>
                    <th>{t3}</th>
                    <th>{t4}</th>
                    <th>{t5}</th>
                    <th>{t6}</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={1}
                        name={c1}
                        onChange={handlerData}
                        required={require}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={1}
                        name={c2}
                        onChange={handlerData}
                        required={require}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={1}
                        name={c3}
                        onChange={handlerData}
                        required={require}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={1}
                        name={c4}
                        onChange={handlerData}
                        required={require}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={1}
                        name={c5}
                        onChange={handlerData}
                        required={require}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={1}
                        name={c6}
                        onChange={handlerData}
                        required={require}
                      />
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={2}
                        name={c1}
                        onChange={handlerData}
                        required={require}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={2}
                        name={c2}
                        onChange={handlerData}
                        required={require}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={2}
                        name={c3}
                        onChange={handlerData}
                        required={require}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={2}
                        name={c4}
                        onChange={handlerData}
                        required={require}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={2}
                        name={c5}
                        onChange={handlerData}
                        required={require}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={2}
                        name={c6}
                        onChange={handlerData}
                        required={require}
                      />
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={3}
                        name={c1}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={3}
                        name={c2}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={3}
                        name={c3}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={3}
                        name={c4}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={3}
                        name={c5}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={3}
                        name={c6}
                        onChange={handlerData}
                      />
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={4}
                        name={c1}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={4}
                        name={c2}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={4}
                        name={c3}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={4}
                        name={c4}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={4}
                        name={c5}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={4}
                        name={c6}
                        onChange={handlerData}
                      />
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={5}
                        name={c1}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={5}
                        name={c2}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={5}
                        name={c3}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={5}
                        name={c4}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={5}
                        name={c5}
                        onChange={handlerData}
                      />
                    </td>
                    <td>
                      <input
                        className="input"
                        type="text"
                        id={5}
                        name={c6}
                        onChange={handlerData}
                      />
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </>
    );
  };

export default ScheduleOfODrivers;